// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo-edge/projects/gloo/api/v1/options/shadowing/shadowing.proto

package shadowing

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Specifies traffic shadowing configuration for the associated route.
// If set, Envoy will send a portion of the route's traffic to the shadowed upstream. This can be a useful way to
// preview a new service's behavior before putting the service in the critical path.
// Note that this plugin is only applicable to routes with upstream destinations (not redirect or direct response routes).
// See here for additional information on Envoy's shadowing capabilities: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction-requestmirrorpolicy
type RouteShadowing struct {
	// The upstream to which the shadowed traffic should be sent.
	Upstream *core.ResourceRef `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// This should be a value between 0.0 and 100.0, with up to 6 significant digits.
	Percentage           float32  `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteShadowing) Reset()         { *m = RouteShadowing{} }
func (m *RouteShadowing) String() string { return proto.CompactTextString(m) }
func (*RouteShadowing) ProtoMessage()    {}
func (*RouteShadowing) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a373856eb74d63, []int{0}
}
func (m *RouteShadowing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteShadowing.Unmarshal(m, b)
}
func (m *RouteShadowing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteShadowing.Marshal(b, m, deterministic)
}
func (m *RouteShadowing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteShadowing.Merge(m, src)
}
func (m *RouteShadowing) XXX_Size() int {
	return xxx_messageInfo_RouteShadowing.Size(m)
}
func (m *RouteShadowing) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteShadowing.DiscardUnknown(m)
}

var xxx_messageInfo_RouteShadowing proto.InternalMessageInfo

func (m *RouteShadowing) GetUpstream() *core.ResourceRef {
	if m != nil {
		return m.Upstream
	}
	return nil
}

func (m *RouteShadowing) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func init() {
	proto.RegisterType((*RouteShadowing)(nil), "shadowing.options.gloo.solo.io.RouteShadowing")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo-edge/projects/gloo/api/v1/options/shadowing/shadowing.proto", fileDescriptor_51a373856eb74d63)
}

var fileDescriptor_51a373856eb74d63 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x95, 0x0a, 0x21, 0x14, 0x24, 0x86, 0x88, 0xa1, 0xed, 0x10, 0x55, 0x4c, 0x5d, 0x6a,
	0x0b, 0x10, 0x2f, 0xc0, 0xc2, 0x4c, 0xba, 0xb1, 0x39, 0xc9, 0x8d, 0x6b, 0x9a, 0xe6, 0x58, 0xf6,
	0x35, 0xed, 0x23, 0xf1, 0x08, 0x3c, 0x0f, 0xef, 0xc0, 0x8e, 0xf2, 0x47, 0x59, 0x3a, 0x74, 0xbb,
	0x3a, 0xe7, 0xf8, 0x9e, 0xcf, 0x37, 0x5e, 0x6b, 0xc3, 0x9b, 0x90, 0x8b, 0x02, 0x3b, 0xe9, 0x51,
	0x63, 0x65, 0x20, 0x75, 0x0d, 0xac, 0xa8, 0xd4, 0x24, 0xad, 0xc3, 0x3b, 0x15, 0xec, 0x3b, 0x49,
	0x2a, 0x6b, 0xe4, 0xc7, 0xbd, 0x84, 0x65, 0x83, 0xc6, 0x4b, 0xbf, 0x51, 0x25, 0xf6, 0xa6, 0xd1,
	0xc7, 0x49, 0x58, 0x07, 0x46, 0x92, 0x1e, 0x85, 0x21, 0x2c, 0xda, 0x05, 0xa2, 0x2d, 0x10, 0x06,
	0xf3, 0x5b, 0x0d, 0x8d, 0x2e, 0x2a, 0xdb, 0xa9, 0x7f, 0x35, 0x4f, 0x35, 0xa0, 0xeb, 0xae, 0x94,
	0x91, 0x87, 0x4a, 0xee, 0x9d, 0xb2, 0x96, 0x9c, 0x3f, 0xe5, 0x97, 0xc1, 0xa9, 0x76, 0xfb, 0xe0,
	0xcf, 0x3a, 0xfe, 0xad, 0xe1, 0x11, 0xd4, 0x51, 0x35, 0x58, 0x09, 0x1d, 0xb8, 0xef, 0xa3, 0x03,
	0xf7, 0xda, 0x9d, 0x8e, 0x6f, 0x32, 0x04, 0xa6, 0xf5, 0xc8, 0x9a, 0x3c, 0xc5, 0x57, 0xc1, 0x7a,
	0x76, 0xa4, 0x76, 0xd3, 0x68, 0x11, 0x2d, 0xaf, 0x1f, 0x66, 0xa2, 0x80, 0xa3, 0x91, 0x5b, 0x64,
	0xe4, 0x11, 0x5c, 0x41, 0x19, 0x55, 0xd9, 0x5f, 0x34, 0x49, 0xe3, 0xd8, 0x92, 0x2b, 0xa8, 0x61,
	0xa5, 0x69, 0x3a, 0x59, 0x44, 0xcb, 0x49, 0xf6, 0x4f, 0x79, 0x7e, 0xfd, 0xfa, 0xb9, 0x88, 0x3e,
	0xbf, 0xd3, 0xe8, 0xed, 0xe5, 0x8c, 0x63, 0xdb, 0xad, 0x3e, 0x79, 0xf0, 0xfc, 0xb2, 0xfb, 0xc2,
	0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x34, 0x52, 0x54, 0xbe, 0x01, 0x00, 0x00,
}

func (this *RouteShadowing) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RouteShadowing)
	if !ok {
		that2, ok := that.(RouteShadowing)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Upstream.Equal(that1.Upstream) {
		return false
	}
	if this.Percentage != that1.Percentage {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
