// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo-edge/projects/gloo/api/v1/endpoint.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//
//Endpoints represent dynamically discovered address/ports where an upstream service is listening
type Endpoint struct {
	// List of the upstreams the endpoint belongs to
	Upstreams []*core.ResourceRef `protobuf:"bytes,1,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	// Address of the endpoint (ip or hostname)
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// listening port for the endpoint
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// hostname to use for the endpoint (e.g., auto host rewrite) if provided.
	Hostname string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// configuration for health checking the endpoint.
	HealthCheck *HealthCheckConfig `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	// Metadata contains the object metadata for this resource
	Metadata             core.Metadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb359bb428664aa4, []int{0}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetUpstreams() []*core.ResourceRef {
	if m != nil {
		return m.Upstreams
	}
	return nil
}

func (m *Endpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Endpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Endpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Endpoint) GetHealthCheck() *HealthCheckConfig {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

func (m *Endpoint) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

type HealthCheckConfig struct {
	// hostname to use for the endpoint health checks if provided.
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckConfig) Reset()         { *m = HealthCheckConfig{} }
func (m *HealthCheckConfig) String() string { return proto.CompactTextString(m) }
func (*HealthCheckConfig) ProtoMessage()    {}
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb359bb428664aa4, []int{1}
}
func (m *HealthCheckConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckConfig.Unmarshal(m, b)
}
func (m *HealthCheckConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckConfig.Marshal(b, m, deterministic)
}
func (m *HealthCheckConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckConfig.Merge(m, src)
}
func (m *HealthCheckConfig) XXX_Size() int {
	return xxx_messageInfo_HealthCheckConfig.Size(m)
}
func (m *HealthCheckConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckConfig proto.InternalMessageInfo

func (m *HealthCheckConfig) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "gloo.solo.io.Endpoint")
	proto.RegisterType((*HealthCheckConfig)(nil), "gloo.solo.io.HealthCheckConfig")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo-edge/projects/gloo/api/v1/endpoint.proto", fileDescriptor_bb359bb428664aa4)
}

var fileDescriptor_bb359bb428664aa4 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbd, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0xb9, 0x86, 0xdb, 0x3a, 0x97, 0x01, 0x0b, 0xa1, 0xdc, 0x48, 0xdc, 0x1b, 0xdd, 0x29,
	0xcb, 0xb5, 0x45, 0x11, 0x02, 0xb1, 0x80, 0x5a, 0x21, 0xb1, 0xb0, 0x64, 0x64, 0x41, 0x6e, 0x72,
	0x9a, 0x84, 0x36, 0x39, 0x96, 0xed, 0xa2, 0xce, 0x7d, 0x1a, 0xc4, 0x13, 0xf0, 0x08, 0x3c, 0x05,
	0x03, 0x6f, 0xd0, 0x81, 0x1d, 0xc5, 0x4d, 0x5a, 0x0a, 0x62, 0x60, 0x3b, 0xe7, 0x7c, 0xdf, 0xe7,
	0xf3, 0xf3, 0x99, 0xbd, 0x2e, 0x6b, 0x57, 0xad, 0xe7, 0x22, 0xc7, 0x46, 0x5a, 0x5c, 0xe1, 0x6d,
	0x8d, 0xb2, 0x5c, 0x21, 0xde, 0x42, 0x51, 0x82, 0xd4, 0x06, 0x3f, 0x42, 0xee, 0xac, 0x2f, 0x49,
	0xa5, 0x6b, 0xf9, 0xe9, 0x89, 0x84, 0xb6, 0xd0, 0x58, 0xb7, 0x4e, 0x68, 0x83, 0x0e, 0xf9, 0x45,
	0x87, 0x89, 0x4e, 0x2b, 0x6a, 0x8c, 0x1f, 0x96, 0x58, 0xa2, 0x07, 0x64, 0x17, 0xed, 0x39, 0x31,
	0x87, 0x8d, 0xdb, 0x17, 0x61, 0xd3, 0xeb, 0xe2, 0x2b, 0xdf, 0x6e, 0x59, 0xbb, 0xe1, 0xdd, 0x06,
	0x9c, 0x2a, 0x94, 0x53, 0x3d, 0x7e, 0xf9, 0x27, 0x6e, 0x60, 0xf1, 0x2f, 0xe9, 0x90, 0xef, 0xf1,
	0x9b, 0x2f, 0x01, 0x1b, 0xbd, 0xe9, 0xa7, 0xe4, 0xcf, 0xd9, 0x78, 0xad, 0xad, 0x33, 0xa0, 0x1a,
	0x1b, 0x91, 0xe4, 0x2c, 0x0d, 0x27, 0x97, 0x22, 0x47, 0x03, 0xc3, 0xcc, 0x22, 0x03, 0x8b, 0x6b,
	0x93, 0x43, 0x06, 0x8b, 0xec, 0xc8, 0xe5, 0x11, 0x3b, 0x57, 0x45, 0x61, 0xc0, 0xda, 0x28, 0x48,
	0x48, 0x3a, 0xce, 0x86, 0x94, 0x73, 0x46, 0x35, 0x1a, 0x17, 0x9d, 0x25, 0x24, 0xbd, 0x9f, 0xf9,
	0x98, 0xc7, 0x6c, 0x54, 0xa1, 0x75, 0xad, 0x6a, 0x20, 0xa2, 0x9e, 0x7e, 0xc8, 0xf9, 0x94, 0x5d,
	0x54, 0xa0, 0x56, 0xae, 0xfa, 0x90, 0x57, 0x90, 0x2f, 0xa3, 0xbb, 0x09, 0x49, 0xc3, 0xc9, 0xb5,
	0xf8, 0xfd, 0x72, 0xe2, 0xad, 0x67, 0xcc, 0x3a, 0xc2, 0x0c, 0xdb, 0x45, 0x5d, 0x66, 0x61, 0x75,
	0x2c, 0xf1, 0x17, 0x6c, 0x34, 0x1c, 0x28, 0x3a, 0xf7, 0xfa, 0x47, 0xa7, 0x5b, 0xbc, 0xeb, 0xd1,
	0x29, 0xfd, 0xf6, 0xfd, 0xfa, 0x4e, 0x76, 0x60, 0xbf, 0x7c, 0xbc, 0xdd, 0x51, 0xca, 0x02, 0xd0,
	0xdb, 0x1d, 0x0d, 0xf9, 0x78, 0xb0, 0xcf, 0x6e, 0x77, 0x34, 0x48, 0xc9, 0x8d, 0x64, 0x0f, 0xfe,
	0x6a, 0x7d, 0xb2, 0x0d, 0x39, 0xdd, 0x66, 0xfa, 0xea, 0xeb, 0x4f, 0x4a, 0x3e, 0xff, 0xb8, 0x22,
	0xef, 0x9f, 0xfd, 0xc7, 0xe7, 0xd1, 0xcb, 0xb2, 0x77, 0x6b, 0x7e, 0xcf, 0xbb, 0xf4, 0xf4, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x86, 0xbc, 0x76, 0x7c, 0x02, 0x00, 0x00,
}

func (this *Endpoint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Endpoint)
	if !ok {
		that2, ok := that.(Endpoint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Upstreams) != len(that1.Upstreams) {
		return false
	}
	for i := range this.Upstreams {
		if !this.Upstreams[i].Equal(that1.Upstreams[i]) {
			return false
		}
	}
	if this.Address != that1.Address {
		return false
	}
	if this.Port != that1.Port {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	if !this.HealthCheck.Equal(that1.HealthCheck) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HealthCheckConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckConfig)
	if !ok {
		that2, ok := that.(HealthCheckConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
