// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo-edge/projects/gloo/api/v1/extensions.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Extensions struct {
	Configs              map[string]*types.Struct `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Extensions) Reset()         { *m = Extensions{} }
func (m *Extensions) String() string { return proto.CompactTextString(m) }
func (*Extensions) ProtoMessage()    {}
func (*Extensions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3475a9569899cbf, []int{0}
}
func (m *Extensions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extensions.Unmarshal(m, b)
}
func (m *Extensions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extensions.Marshal(b, m, deterministic)
}
func (m *Extensions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extensions.Merge(m, src)
}
func (m *Extensions) XXX_Size() int {
	return xxx_messageInfo_Extensions.Size(m)
}
func (m *Extensions) XXX_DiscardUnknown() {
	xxx_messageInfo_Extensions.DiscardUnknown(m)
}

var xxx_messageInfo_Extensions proto.InternalMessageInfo

func (m *Extensions) GetConfigs() map[string]*types.Struct {
	if m != nil {
		return m.Configs
	}
	return nil
}

type Extension struct {
	Config               *types.Struct `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Extension) Reset()         { *m = Extension{} }
func (m *Extension) String() string { return proto.CompactTextString(m) }
func (*Extension) ProtoMessage()    {}
func (*Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3475a9569899cbf, []int{1}
}
func (m *Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extension.Unmarshal(m, b)
}
func (m *Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extension.Marshal(b, m, deterministic)
}
func (m *Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extension.Merge(m, src)
}
func (m *Extension) XXX_Size() int {
	return xxx_messageInfo_Extension.Size(m)
}
func (m *Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_Extension proto.InternalMessageInfo

func (m *Extension) GetConfig() *types.Struct {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*Extensions)(nil), "gloo.solo.io.Extensions")
	proto.RegisterMapType((map[string]*types.Struct)(nil), "gloo.solo.io.Extensions.ConfigsEntry")
	proto.RegisterType((*Extension)(nil), "gloo.solo.io.Extension")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo-edge/projects/gloo/api/v1/extensions.proto", fileDescriptor_c3475a9569899cbf)
}

var fileDescriptor_c3475a9569899cbf = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x56, 0x2b, 0xdd, 0xf6, 0x20, 0x8b, 0x60, 0x08, 0x22, 0xa1, 0x20, 0xe4, 0x92,
	0x59, 0xac, 0x08, 0x22, 0x42, 0xa1, 0xd2, 0x17, 0x48, 0x6f, 0xde, 0x9a, 0xb8, 0x5d, 0xd7, 0xc6,
	0x4c, 0xc8, 0x6e, 0x4a, 0xfa, 0x3a, 0x9e, 0x7c, 0x04, 0x9f, 0xc7, 0x77, 0xf0, 0x2e, 0xd9, 0x4d,
	0x6b, 0x4e, 0x82, 0xb7, 0x61, 0xe6, 0xfb, 0xff, 0x9f, 0x9f, 0xa1, 0x73, 0xa9, 0xcc, 0x4b, 0x95,
	0x40, 0x8a, 0x6f, 0x5c, 0x63, 0x86, 0x91, 0x42, 0x2e, 0x33, 0xc4, 0x48, 0x3c, 0x4b, 0xc1, 0x8b,
	0x12, 0x5f, 0x45, 0x6a, 0xb4, 0x5d, 0xf1, 0x55, 0xa1, 0xf8, 0xf6, 0x9a, 0x8b, 0xda, 0x88, 0x5c,
	0x2b, 0xcc, 0x35, 0x14, 0x25, 0x1a, 0x64, 0xe3, 0xe6, 0x0a, 0x8d, 0x1a, 0x14, 0xfa, 0x17, 0x12,
	0x51, 0x66, 0x56, 0x6b, 0x30, 0xa9, 0xd6, 0x5c, 0x9b, 0xb2, 0x4a, 0x8d, 0x63, 0xfd, 0x33, 0x89,
	0x12, 0xed, 0xc8, 0x9b, 0xa9, 0xdd, 0x32, 0x51, 0x1b, 0xb7, 0x14, 0x75, 0x4b, 0x4e, 0xde, 0x09,
	0xa5, 0x8b, 0x43, 0x14, 0x9b, 0xd1, 0x93, 0x14, 0xf3, 0xb5, 0x92, 0xda, 0x23, 0x41, 0x3f, 0x1c,
	0x4d, 0xaf, 0xa0, 0x1b, 0x0b, 0xbf, 0x28, 0x3c, 0x3a, 0x6e, 0x91, 0x9b, 0x72, 0x17, 0xef, 0x55,
	0xfe, 0x92, 0x8e, 0xbb, 0x07, 0x76, 0x4a, 0xfb, 0x1b, 0xb1, 0xf3, 0x48, 0x40, 0xc2, 0x61, 0xdc,
	0x8c, 0x2c, 0xa2, 0xc7, 0xdb, 0x55, 0x56, 0x09, 0xaf, 0x17, 0x90, 0x70, 0x34, 0x3d, 0x07, 0xd7,
	0x04, 0xf6, 0x4d, 0x60, 0x69, 0x9b, 0xc4, 0x8e, 0xba, 0xef, 0xdd, 0x91, 0xc9, 0x03, 0x1d, 0x1e,
	0x82, 0x19, 0xa7, 0x03, 0x17, 0x66, 0x4d, 0xff, 0x30, 0x68, 0xb1, 0xf9, 0xec, 0xf3, 0xfb, 0x88,
	0x7c, 0x7c, 0x5d, 0x92, 0xa7, 0xdb, 0x7f, 0xbc, 0xa1, 0xd8, 0xc8, 0xf6, 0x15, 0xc9, 0xc0, 0x3a,
	0xdf, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x29, 0x6a, 0xfd, 0x47, 0xc6, 0x01, 0x00, 0x00,
}

func (this *Extensions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Extensions)
	if !ok {
		that2, ok := that.(Extensions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Configs) != len(that1.Configs) {
		return false
	}
	for i := range this.Configs {
		if !this.Configs[i].Equal(that1.Configs[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Extension) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Extension)
	if !ok {
		that2, ok := that.(Extension)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Config.Equal(that1.Config) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
